### ISSUE TITLE
Unable to unmount shares under /media

### ISSUE THREAD

**Issue by bviktor** [noobient/noobuntu#13]
PolicyKit?

https://bugs.launchpad.net/ubuntu/+source/libpam-mount/+bug/117736

> With pam mount log in. Then log out. Verify mounts are still up. Bring down networking. Log in (using su is fine). The terminal hangs. You never log in.

Does this apply here?

SATA solution:

```
[SATA Access]
Identity=unix-group:plugdev
Action=org.freedesktop.udisks2.filesystem-mount-system
ResultAny=no
ResultInactive=no
ResultActive=yes
```

```
- name: Configure SATA disk mount
  template:
    src: 99-sata-access.pkla.j2
    dest: /etc/polkit-1/localauthority/20-org.d/99-sata-access.pkla
    mode: 0640
    owner: root
```

`/usr/share/polkit-1/actions/org.freedesktop.UDisks2.policy`

Actually it won't work if it's mounted under `$HOME` either.
