### ISSUE TITLE
Optimize batch apt installs

### ISSUE THREAD

**Issue by bviktor** [noobient/noobuntu#28]
```
- apt:
    name: "{{ item }}"
    state: latest
  loop:
    - mc
    - git

```

vs

```
- apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libgles2-mesa-dev
    - libgles2-mesa
```
