### ISSUE TITLE
firewalld rework

### ISSUE THREAD

**Issue by bviktor** [noobient/noobuntu#93]
Use vars instead of loop items. That allows for calling firewalld with arrays.

Porting:

---

Single items:

```
- include_role:
    name: firewalld
  loop:
  - { service: 'tftp' }
```

becomes:

```
- include_role:
    name: firewalld
  vars:
  - service: 'tftp'
```

---

Multiple items:

```
- include_role:
    name: firewalld
  loop:
  - { service: 'k8s-api-rw', port: '10250/tcp' }
  - { service: 'k8s-api-ro', port: '10255/tcp' }
```

becomes:

```
- include_role:
    name: firewalld
  vars:
  - service: "{{ item.service }}"
  - port: "{{ item.port }}"
  loop:
  - { service: 'k8s-api-rw', port: '10250/tcp' }
  - { service: 'k8s-api-ro', port: '10255/tcp' }
```
